import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class Language {
  final String code;
  final String name;
  final String nativeName;

  const Language({
    required this.code,
    required this.name,
    required this.nativeName,
  });
}

class LanguageService extends ChangeNotifier {
  static final LanguageService _instance = LanguageService._internal();
  factory LanguageService() => _instance;
  LanguageService._internal() {
    _loadSavedLanguage();
  }

  static const List<Language> supportedLanguages = [
    Language(code: 'en', name: 'English', nativeName: 'English'),
    Language(code: 'hi', name: 'Hindi', nativeName: 'हिंदी'),
    Language(code: 'mr', name: 'Marathi', nativeName: 'मराठी'),
    Language(code: 'te', name: 'Telugu', nativeName: 'తెలుగు'),
    Language(code: 'ta', name: 'Tamil', nativeName: 'தமிழ்'),
    Language(code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം'),
  ];

  Language _currentLanguage = supportedLanguages[0]; // Default to English

  Language get currentLanguage => _currentLanguage;

  // Load saved language from SharedPreferences
  Future<void> _loadSavedLanguage() async {
    try {
      final prefs = await SharedPreferences.getInstance();
      final savedLanguageCode = prefs.getString('selected_language');
      
      if (savedLanguageCode != null) {
        final savedLanguage = supportedLanguages.firstWhere(
          (lang) => lang.code == savedLanguageCode,
          orElse: () => supportedLanguages[0],
        );
        _currentLanguage = savedLanguage;
        notifyListeners();
      }
    } catch (e) {
      debugPrint('Error loading saved language: $e');
    }
  }

  // Save language preference and notify listeners across all screens
  Future<void> changeLanguage(Language language) async {
    _currentLanguage = language;
    notifyListeners();
    
    try {
      final prefs = await SharedPreferences.getInstance();
      await prefs.setString('selected_language', language.code);
    } catch (e) {
      debugPrint('Error saving language preference: $e');
    }
  }

  String getTranslation(String key) {
    final dict = _getTranslations()[_currentLanguage.code];
    if (dict != null && dict.containsKey(key) && dict[key]!.isNotEmpty) {
      return dict[key]!;
    }
    // Fallback to English if translation is missing for the key
    final enDict = _getTranslations()['en'];
    if (enDict != null && enDict.containsKey(key)) {
      return enDict[key]!;
    }
    return key;
  }

  /// Returns all canonical keys defined in English dictionary
  static List<String> getAllCanonicalKeys() => _getTranslations()['en']?.keys.toList() ?? [];

  /// Returns raw translations dictionary for a specific language code
  static Map<String, String>? getTranslationsFor(String code) => _getTranslations()[code];

  /// Localizes any raw status string (e.g. 'submitted', 'in_progress', 'resolved')
  String localizeStatus(dynamic rawStatus) {
    if (rawStatus == null) return getTranslation('status_submitted');
    final str = rawStatus.toString().toLowerCase().trim().replaceAll('reportstatus.', '').replaceAll(' ', '_');
    
    if (str.contains('submit') && !str.contains('resolution')) {
      return getTranslation('status_submitted');
    }
    if (str.contains('review')) {
      return getTranslation('status_under_review');
    }
    if (str.contains('assign')) {
      return getTranslation('status_assigned');
    }
    if (str.contains('progress')) {
      return getTranslation('status_in_progress');
    }
    if (str.contains('resolution_submit') || str.contains('remediation')) {
      return getTranslation('status_resolution_submitted');
    }
    if (str.contains('citizen_verif') || str.contains('verification')) {
      return getTranslation('status_citizen_verification');
    }
    if (str.contains('reopen')) {
      return getTranslation('status_reopened');
    }
    if (str.contains('resolve') || str.contains('verif')) {
      return getTranslation('status_resolved');
    }
    if (str.contains('close')) {
      return getTranslation('status_closed');
    }
    if (str.contains('reject')) {
      return getTranslation('status_rejected');
    }

    final lookup = getTranslation('status_$str');
    if (lookup != 'status_$str') return lookup;
    return getTranslation('status_submitted');
  }

  /// Localizes any raw priority string (e.g. 'High', 'Medium', 'Low', 'Critical')
  String localizePriority(dynamic rawPriority) {
    if (rawPriority == null) return getTranslation('priority_medium');
    final str = rawPriority.toString().toLowerCase().trim().replaceAll('reportpriority.', '');
    
    if (str.contains('high')) return getTranslation('priority_high');
    if (str.contains('crit')) return getTranslation('priority_critical');
    if (str.contains('low')) return getTranslation('priority_low');
    return getTranslation('priority_medium');
  }

  /// Localizes any category ID or display name
  String localizeCategory(String categoryIdOrName) {
    final clean = categoryIdOrName.trim().toLowerCase().replaceAll('-', '_').replaceAll(' ', '_');
    final direct = getTranslation('cat_$clean');
    if (direct != 'cat_$clean') return direct;

    if (clean.contains('pothole') || clean.contains('road') || clean.contains('footpath')) {
      return getTranslation('cat_potholes_roads');
    }
    if (clean.contains('water') || clean.contains('pipe')) {
      return getTranslation('cat_water_drainage');
    }
    if (clean.contains('drain') || clean.contains('sewag') || clean.contains('manhole')) {
      return getTranslation('cat_drainage_sewage');
    }
    if (clean.contains('electric') || clean.contains('light') || clean.contains('wire')) {
      return getTranslation('cat_electricity_streetlights');
    }
    if (clean.contains('garbage') || clean.contains('waste') || clean.contains('trash') || clean.contains('sanitation')) {
      return getTranslation('cat_waste_management');
    }
    if (clean.contains('safety') || clean.contains('hazard') || clean.contains('fire')) {
      return getTranslation('cat_safety_hazard');
    }
    if (clean.contains('park') || clean.contains('tree')) {
      return getTranslation('cat_parks_trees');
    }
    if (clean.contains('encroach') || clean.contains('illegal')) {
      return getTranslation('cat_illegal_encroachment');
    }

    return getTranslation('cat_other');
  }

  static Map<String, Map<String, String>> _getTranslations() {
    return {
      // =======================================================================
      // ENGLISH (Canonical)
      // =======================================================================
      'en': {
        // App Identity & Headers
        'app_name': 'CivicResolve',
        'app_slogan': 'Building Better Communities Together',
        'app_tagline': 'Municipal Citizen Grievance Redressal Portal',
        'welcome_to_civicresolve': 'Welcome to CivicResolve',
        'welcome_subtitle': 'Report civic issues, track real-time resolution, and help make our city cleaner and safer.',
        'municipal_citizen_services': 'Municipal Citizen Services',
        'municipal_admin_control': 'Municipal Administrative Control',
        'official_civic_service': 'Official Civic Redressal Service • Public Grievance Cell',

        // Authentication & Roles
        'citizen': 'Citizen',
        'public_servant': 'Government / Field Officer',
        'role_citizen_desc': 'Report civic issues & track progress in your neighborhood',
        'role_officer_desc': 'Municipal staff & field resolution team login',
        'log_in': 'Log In',
        'sign_up': 'Sign Up',
        'sign_in': 'Sign In',
        'new_citizen_register': 'New Citizen? Register Here',
        'already_have_account': 'Already have an account? Sign In',
        'login_subtitle': 'Welcome back, please enter your details to continue.',
        'signup_subtitle': 'Create your citizen profile to report and track municipal issues.',
        'full_name': 'Full Name',
        'full_name_hint': 'Enter your official name',
        'phone_number': 'Mobile Number',
        'phone_hint': 'Enter 10-digit mobile number',
        'email': 'Email Address',
        'email_hint': 'Enter your email address',
        'password': 'Password',
        'password_hint': 'Enter your password',
        'confirm_password': 'Confirm Password',
        'district': 'District / Municipality',
        'district_hint': 'e.g., Solapur Municipal Corporation',
        'ward': 'Ward / Zone No.',
        'ward_hint': 'e.g., Ward 14',
        'remember_me': 'Remember me',
        'forgot_password': 'Forgot Password?',
        'or_continue_with': 'Or continue with',
        'dont_have_account': "Don't have an account?",
        'create_account': 'Create Citizen Account',
        'login_to_account': 'Sign In to Your Account',
        'logging_in': 'Signing in...',
        'creating_account': 'Creating citizen account...',
        'login_success': 'Signed in successfully!',
        'signup_success': 'Account created successfully!',
        'invalid_credentials': 'Invalid credentials. Please check your email/password.',
        'fill_required_fields': 'Please fill in all required fields.',
        'logout': 'Log Out',
        'logout_confirm': 'Are you sure you want to log out?',

        // Navigation & Menu
        'nav_home': 'Home',
        'nav_report': 'Report',
        'nav_track': 'Track',
        'nav_map': 'Map',
        'nav_profile': 'Profile',
        'menu': 'Menu',
        'home_dashboard': 'Home Dashboard',
        'track_complaints': 'Track Complaints',
        'nearby_issues_map': 'Nearby Issues Map',
        'local_civic_feed': 'Local Civic Feed',
        'emergency_helpline': 'Emergency Helpline',
        'change_language': 'Change Language',
        'notifications': 'Notifications',
        'settings': 'Settings',
        'help_support': 'Help & Support',

        // Dashboard
        'good_morning': 'Good morning',
        'good_afternoon': 'Good afternoon',
        'good_evening': 'Good evening',
        'report_problem_title': 'Report a Municipal Problem',
        'report_problem_subtitle': 'Potholes, water supply, streetlights, garbage & sanitation',
        'register_new_grievance': 'Register New Grievance',
        'citizen_services': 'Citizen Services',
        'discover_support': 'Discover & support',
        'map_view': 'OpenStreetMap view',
        'live_status_timeline': 'Live status timeline',
        'control_room_police': 'Control room & police',
        'recent_grievances': 'Recent Grievances',
        'view_all': 'View All',
        'no_reports_yet': 'No grievances registered yet',
        'no_reports_desc': 'Submit your first report to help improve municipal services in your area.',
        'refresh_location': 'Refresh Location',
        'my_reports': 'My Complaints',
        'community_reports': 'Community Reports',

        // Grievance Reporting Step Flow
        'select_category_step': 'Step 1 of 3: Select Category',
        'select_issue_category': 'Select the issue category',
        'category_guide': 'Choose the municipal service division that best matches the problem in your area.',
        'municipal_departments': 'Municipal Departments',
        'provide_details_step': 'Step 2 of 3: Provide Details',
        'review_submit_step': 'Step 3 of 3: Review & Submit',
        'selected_category': 'Selected Category',
        'complaint_description': 'Complaint Description *',
        'complaint_desc_hint': 'Describe the civic problem clearly with details like severity, location landmarks, and duration...',
        'photo_evidence': 'Photo Evidence *',
        'upload_photos_max': 'Upload Photos (Max 5)',
        'take_photo': 'Take Photo',
        'choose_from_gallery': 'Choose from Gallery',
        'problem_location': 'Problem Location *',
        'use_current_location': 'Use Current Location',
        'enter_address_hint': 'Enter address or nearby landmarks (e.g., Near City Hospital Gate 2)...',
        'priority': 'Priority',
        'priority_high': 'High',
        'priority_medium': 'Medium',
        'priority_low': 'Low',
        'priority_critical': 'Critical',
        'priority_high_desc': 'Immediate hazard / urgent',
        'priority_medium_desc': 'Standard service request',
        'priority_low_desc': 'Routine maintenance',
        'continue_to_review': 'Continue to Review',
        'submit_complaint': 'SUBMIT COMPLAINT',
        'submitting_complaint': 'Submitting Complaint...',
        'complaint_submitted': 'Complaint Submitted',
        'complaint_submitted_desc': 'Your complaint has been received by CivicResolve and forwarded to municipal authorities.',
        'complaint_ref_id': 'COMPLAINT REFERENCE ID',
        'green_credits_earned': '+10 Green Credits earned for active civic reporting!',
        'what_happens_next': 'What Happens Next?',
        'next_step_1': 'Automated municipal validation & department assignment.',
        'next_step_2': 'Field inspection team dispatched to site.',
        'next_step_3': 'Track real-time progress and photos in "Track My Reports".',
        'track_complaint': 'Track Complaint',
        'return_to_home': 'Return to Home',

        // Categories & Descriptions
        'cat_potholes_roads': 'Roads & Potholes',
        'cat_potholes_roads_desc': 'Potholes, broken roads, damaged footpaths',
        'cat_water_drainage': 'Water Supply & Leaks',
        'cat_water_drainage_desc': 'Pipe bursts, low pressure, contaminated water',
        'cat_drainage_sewage': 'Drainage & Sewage',
        'cat_drainage_sewage_desc': 'Blocked drains, open manholes, overflowing sewage',
        'cat_electricity_streetlights': 'Electricity & Streetlights',
        'cat_electricity_streetlights_desc': 'Faulty streetlights, hanging wires, power failure',
        'cat_waste_management': 'Garbage & Sanitation',
        'cat_waste_management_desc': 'Uncollected garbage, open dumping, bin overflow',
        'cat_safety_hazard': 'Public Safety Hazards',
        'cat_safety_hazard_desc': 'Dangerous structures, open pits, fire hazards',
        'cat_parks_trees': 'Parks & Fallen Trees',
        'cat_parks_trees_desc': 'Overgrown trees, branch clearing, park upkeep',
        'cat_illegal_encroachment': 'Illegal Encroachment',
        'cat_illegal_encroachment_desc': 'Footpath blocking, unauthorized construction',
        'cat_other': 'Other Grievance',
        'cat_other_desc': 'General civic issues not listed above',

        // Tracking & Status Lifecycle
        'tracking_title': 'Track Complaints',
        'all_reports': 'All Reports',
        'active_reports': 'Active',
        'resolved_reports': 'Resolved',
        'status_submitted': 'Submitted',
        'status_under_review': 'Under Review',
        'status_assigned': 'Assigned',
        'status_in_progress': 'In Progress',
        'status_resolution_submitted': 'Resolution Submitted',
        'status_citizen_verification': 'Citizen Verification',
        'status_resolved': 'Resolved',
        'status_verified': 'Verified',
        'status_closed': 'Closed',
        'status_reopened': 'Reopened',
        'status_rejected': 'Rejected',
        'assigned_officer': 'Assigned Officer',
        'field_team': 'Field Team',
        'expected_resolution': 'Expected Resolution (SLA)',
        'hours': 'hours',
        'days': 'days',
        'verify_resolution': 'Verify Resolution',
        'confirm_resolved': 'Yes, Issue Resolved',
        'not_resolved_reopen': 'Still Not Fixed (Reopen)',
        'resolution_notes': 'Officer Resolution Notes',
        'resolution_evidence': 'Work Proof Evidence',

        // Civic Feed & Community Map
        'civic_feed_title': 'Local Civic Feed',
        'nearby_issues': 'Nearby Civic Issues',
        'support_issue': 'Support',
        'supported': 'Supported',
        'upvotes': 'supporters',
        'filter_all': 'All',
        'filter_nearby': 'Nearby (2km)',
        'filter_trending': 'Most Supported',
        'distance_away': 'away',
        'map_layers': 'Map Layers',
        'legend': 'Legend',

        // Profile & Credits
        'my_profile': 'My Profile',
        'edit_profile': 'Edit Profile',
        'green_points': 'Civic Green Points',
        'total_reports': 'Total Reports',
        'resolved_count': 'Resolved',
        'in_progress_count': 'In Progress',
        'account_settings': 'Account Settings',
        'privacy_policy': 'Privacy Policy',
        'terms_of_service': 'Terms of Service',

        // Emergency Helpline
        'emergency_contacts': 'Emergency Helpline Numbers',
        'ambulance': 'Ambulance (Medical)',
        'fire_brigade': 'Fire Brigade',
        'police_control': 'Police Control Room',
        'municipal_helpline': 'Municipal 24x7 Helpline',
        'disaster_mgmt': 'Disaster Management Cell',

        // System, Feedback, Errors & Permissions
        'loading': 'Loading...',
        'please_wait': 'Please wait...',
        'network_error': 'Network connection error. Please try again.',
        'location_error': 'Location unavailable. Please enable GPS.',
        'permission_required': 'Permission Required',
        'camera_permission_msg': 'Camera and storage permissions are required to attach photo evidence.',
        'success': 'Success',
        'error': 'Error',
        'retry': 'Retry',
        'cancel': 'Cancel',
        'confirm': 'Confirm',
        'close': 'Close',
        'language_settings': 'Language Settings',
        'choose_language': 'Choose Your Language',
        'language_changed_to': 'Language changed to',

        // Additional Auth & Login Keys
        'app_tagline_login': 'Empowering communities, one report at a time.',
        'citizen_tab': 'Citizen',
        'field_officer_tab': 'Field Officer',
        'sign_in_tab': 'Sign In (Aadhaar/OTP)',
        'sign_up_tab': 'New Citizen Sign Up',
        'citizen_login_header': 'Citizen Login',
        'field_officer_login_header': 'Field Officer / Contractor Login',
        'create_account_header': 'Create Citizen Account',
        'join_municipal_desc': 'Join your municipal zone as a verified citizen contributor (Score 0 • 🌱 Civic Starter)',
        'full_legal_name_hint': 'Full Legal Name (e.g. Vikram Patil)',
        'mobile_number_hint': '10-digit Mobile Number',
        'email_address_hint': 'Email Address (e.g. name@example.com)',
        'password_char_hint': 'Password (min 6 characters)',
        'district_city_hint': 'District / City',
        'ward_area_hint': 'Ward / Area',
        'register_enter_btn': 'Register & Enter Portal',
        'aadhaar_input_hint': '12-digit Aadhaar Number',
        'login_with_aadhaar_btn': 'Login with Aadhaar',
        'otp_sent_card_title': 'OTP sent to your mobile',
        'otp_input_hint': '6-digit OTP (e.g. 123456)',
        'resend_otp_in_text': 'Resend OTP in',
        'can_resend_otp_text': 'You can resend OTP now',
        'resend_btn': 'Resend',
        'verify_login_btn': 'Verify & Login',
        'change_aadhaar_btn': 'Change Aadhaar Number',
        'officer_id_hint': 'Officer ID / Email (e.g. demo.officer@civicresolve.gov)',
        'evaluator_access_title': 'EVALUATOR QUICK ACCESS',
        'evaluator_access_desc': 'One-tap authenticated Citizen session for hackathon evaluation and live feature testing.',
        'evaluator_access_citizen_desc': 'One-tap authenticated Citizen session for hackathon evaluation and live feature testing.',
        'evaluator_access_officer_desc': 'One-tap authenticated Field Officer session for municipal field-worker evaluation and live task tracking.',
        'one_tap_demo_btn': '⚡ One-Tap Judge / Demo Login',
        'one_tap_citizen_demo_btn': '⚡ One-Tap Citizen Demo Login',
        'one_tap_officer_demo_btn': '⚡ One-Tap Field Officer Demo Login',
        
        // Additional Track Keys
        'track_my_complaints': 'Track My Complaints',
        'realtime_action_status': 'Real-time municipal action status',
        'search_complaints_hint': 'Search by ID (#CR-...), title, location...',
        'syncing_status': 'Syncing live status from municipal system...',
        'complaints_found': 'complaints found',
        'live_sync': 'Live Sync',
        'no_matching_complaints': 'No matching complaints',
        'no_complaints_yet_track': 'No complaints yet',
        'try_changing_filters': 'Try changing your search keywords or filter selection.',
        'report_first_track_desc': 'Report your first civic issue and track its resolution here.',
        'clear_filters': 'Clear Filters',
        'report_first_issue_btn': 'Report Your First Issue',
        'sort_newest': 'Newest',
        'sort_oldest': 'Oldest',
        'filter_submitted': 'Submitted',
        'filter_under_review': 'Under Review',
        'filter_assigned': 'Assigned',
        'filter_in_progress': 'In Progress',
        'filter_resolved': 'Resolved',
        'filter_high_priority': 'High Priority',

        // Additional Feed & Map Keys
        'gps_off_showing_public': 'GPS off: showing public grievances',
        'enable_gps': 'Enable GPS',
        'city_wide': 'City-wide',
        'km_radius': 'km radius',
        'sort_most_supported': 'Most Supported',
        'sort_recent': 'Recent',
        'sort_nearby': 'Nearby',
        'search_feed_hint': 'Search feed by title, location or description...',
        'supported_issue_award': 'Supported issue! +2 Civic Impact Points awarded.',
        'live_nearby_issues': 'Live Nearby Civic Issues',
        'gis_reports_near_you': 'Real-time municipal GIS reports near you',
        'gps_unavailable_center': 'GPS unavailable. Showing municipal center.',
        'map_centered_gps': 'Map centered at your current GPS location.',
        'submit_feedback_comments': 'Please enter feedback comments.',
        'feedback_recorded': 'Thank you! Your feedback has been recorded.',
        'enter_feedback_hint': 'Enter feedback details...',
        'rate_experience': 'Rate Resolution Quality',
        'submit_feedback': 'Submit Feedback',

        // Profile & Account Keys
        'verified_citizen': 'Verified Citizen',
        'personal_info': 'Personal Information',
        'date_of_birth': 'Date of Birth',
        'occupation': 'Occupation',
        'member_since': 'Member Since',
        'contact_info': 'Contact Information',
        'address': 'Address',
        'community_activity': 'Community Activity',
        'reports_submitted_count': 'Reports Submitted',
        'community_score': 'Community Score',
        'green_credits_label': 'Green Credits',
        'civic_rewards_contributions': 'Civic Rewards & Contributions',
        'scores_auto_updated_desc': 'Scores are updated automatically when on-site municipal teams verify reports or resolutions.',
        'view_contribution_history_btn': 'VIEW CONTRIBUTION HISTORY',
        'plant_shop_btn': 'Plant Shop',
        'edit_profile_btn': 'Edit Profile',
        'save_changes_btn': 'Save Changes',
        'profile_updated_toast': 'Profile updated successfully',

        // Emergency Contacts Keys
        'police_emergency': 'Police Emergency',
        'police_emergency_desc': 'For immediate police assistance and crime reporting',
        'medical_emergency': 'Medical Emergency',
        'medical_emergency_desc': 'Ambulance and medical emergency services',
        'fire_brigade_desc': 'Fire emergency and rescue operations',
        'disaster_mgmt_desc': 'Natural disaster and emergency management',
        'women_helpline': 'Women Helpline',
        'women_helpline_desc': 'Emergency support for women in distress',
        'child_helpline': 'Child Helpline',
        'child_helpline_desc': 'Emergency support for children in need',
        'tourist_emergency': 'Tourist Emergency',
        'tourist_emergency_desc': 'Tourist assistance and emergency support',
        'senior_helpline': 'Senior Citizen Helpline',
        'senior_helpline_desc': 'Emergency assistance for senior citizens',
        'confirm_call': 'Confirm Call',
        'are_you_sure_call': 'Are you sure you want to call?',
        'call_now': 'Call Now',
        'connecting_to': 'Connecting to',
        'emergency_tips': 'Emergency Tips',
        'stay_calm': 'Stay Calm',
        'stay_calm_desc': 'Keep calm and speak clearly when calling emergency services',
        'know_location': 'Know Your Location',
        'know_location_desc': 'Be ready to provide your exact location or nearby landmarks',
        'have_info_ready': 'Have Important Info Ready',
        'have_info_ready_desc': 'Keep medical information and emergency contacts accessible',
        'follow_instructions': 'Follow Instructions',
        'follow_instructions_desc': "Listen carefully and follow the operator's instructions",
        'dont_hang_up': "Don't Hang Up",
        'dont_hang_up_desc': "Stay on the line until the operator says it's okay to disconnect",

        // Help & Support Keys
        'were_here_to_help': "We're Here to Help",
        'help_intro_desc': 'Find answers, learn how to use the app, and get in touch with our support team',
        'app_guide_tab': 'App Guide',
        'faq_tab': 'FAQ',
        'contact_tab': 'Contact',
        'getting_started': 'Getting Started',
        'step_create_profile': '1. Create Your Profile',
        'step_create_profile_desc': 'Set up your account with basic information and preferences',
        'step_enable_location': '2. Enable Location Services',
        'step_enable_location_desc': 'Allow location access for accurate issue reporting and tracking',
        'step_report_issue': '3. Report an Issue',
        'step_report_issue_desc': 'Take a photo, select category, and submit your report',
        'step_track_progress': '4. Track Progress',
        'step_track_progress_desc': 'Monitor real-time status updates and officer assignment',
        'step_verify_resolution': '5. Verify Resolution',
        'step_verify_resolution_desc': 'Confirm the work done and earn Civic Impact points',

        // Notification Keys
        'clear_all_notifications': 'Clear All Notifications',
        'clear_all_confirm_desc': 'Are you sure you want to clear all notifications? This action cannot be undone.',
        'all_notifications_cleared': 'All notifications cleared',
        'no_notifications_yet': 'No notifications yet',
        'all_caught_up': 'All caught up! You will receive updates about your reports here.',

        // Map View Keys
        'map_view_title': 'Live Nearby Civic Issues',
        'map_view_subtitle': 'Real-time municipal GIS reports near you',
        'category_all': 'All',
        'category_roads': 'Roads',
        'category_water': 'Water',
        'category_electricity': 'Electricity',
        'category_sanitation': 'Sanitation',
        'category_safety': 'Safety',
        'status_active': 'Active',
        'status_all': 'All',
        'view_as_map': 'Map View',
        'view_as_list': 'List View',
        'recenter_map': 'Recenter',

        // Common Form & Dialog Actions
        'edit': 'Edit',
        'camera': 'Camera',
        'gallery': 'Gallery',
        'select_location': 'Select Location',
        'confirm_location': 'Confirm Location',
        'location_confirmed': 'Location confirmed!',
        'quick_options': 'Quick Options',
        'specific_address_label': 'Specific Address or Landmark *',
        'fill_address': 'Please provide the problem address',
        'fill_specific_address': 'Please provide a more specific address',
        'fill_description': 'Please describe the problem',
        'fill_detailed_description': 'Please provide a more detailed description (at least 10 characters)',
        'suggested_priority': 'Suggested priority',
        'ai_review_disclaimer': 'AI-assisted suggestions may be reviewed by municipal staff.',
        'gps_unavailable_fallback': 'Using default municipal center (GPS unavailable). Drag map or edit address to set exact location.',
        'attached_evidence': 'ATTACHED EVIDENCE',
        'no_images_attached': 'No images attached.',
        'replace_photo_to_submit': 'REPLACE PHOTO TO SUBMIT',
        'genuine_report_disclaimer': 'By submitting, you confirm that this report describes a genuine civic issue.',
        'official_municipal_tracking': 'Official Municipal Tracking',
        'seven_stage_lifecycle': '7-Stage Municipal Lifecycle',
        'stage_1_title': '1. Complaint Submitted',
        'stage_1_desc': 'Registered in CivicResolve municipal grievance repository.',
        'stage_2_title': '2. Under Review',
        'stage_2_desc': 'Municipal grievance cell assessing jurisdiction and priority.',
        'stage_3_title': '3. Assigned to Department & Field Officer',
        'stage_3_desc': 'Assigned to jurisdictional municipal maintenance division.',
        'stage_4_title': '4. Field Work In Progress',
        'stage_4_desc': 'Field inspection and maintenance crew active on-site.',
        'stage_5_title': '5. Resolution Submitted',
        'stage_5_desc': 'Field contractor has uploaded photographic remediation proof.',
        'stage_6_title': '6. Resolution Verification',
        'stage_6_desc': 'Evidence verification and citizen feedback sentiment audit.',
        'stage_7_title': '7. Statutory Closure',
        'stage_7_desc': 'Issue successfully resolved and signed off by municipal authority.',
        'submitted_location': 'Submitted Complaint Location',
        'awaiting_field_assignment': 'Awaiting field assignment',
        'on_site_active': 'On Site / Active',
        'assigned_dispatched': 'Assigned / Dispatched',
        'remediation_submitted': 'Remediation Submitted',
        'officer_location_unavailable': 'Officer location unavailable',
        'jurisdictional_cell_assessing': 'Jurisdictional municipal cell assessing',
      },

      // =======================================================================
      // HINDI (हिंदी)
      // =======================================================================
      'hi': {
        // App Identity & Headers
        'app_name': 'CivicResolve',
        'app_slogan': 'बेहतर समुदाय मिलकर बनाते हैं',
        'app_tagline': 'नगर निगम नागरिक शिकायत निवारण पोर्टल',
        'welcome_to_civicresolve': 'CivicResolve में आपका स्वागत है',
        'welcome_subtitle': 'नागरिक समस्याओं की रिपोर्ट करें, रीयल-टाइम समाधान ट्रैक करें और शहर को स्वच्छ व सुरक्षित बनाएं।',
        'municipal_citizen_services': 'नगर निगम नागरिक सेवाएं',
        'municipal_admin_control': 'नगर निगम प्रशासनिक नियंत्रण',
        'official_civic_service': 'आधिकारिक नागरिक निवारण सेवा • जन शिकायत प्रकोष्ठ',

        // Authentication & Roles
        'citizen': 'नागरिक',
        'public_servant': 'शासकीय अधिकारी / फील्ड टीम',
        'role_citizen_desc': 'नागरिक समस्याओं की रिपोर्ट करें और समाधान ट्रैक करें',
        'role_officer_desc': 'नगर निगम अधिकारी और फील्ड टीम लॉगिन',
        'log_in': 'लॉग इन',
        'sign_up': 'साइन अप',
        'sign_in': 'साइन इन करें',
        'new_citizen_register': 'नए नागरिक? यहां पंजीकरण करें',
        'already_have_account': 'पहले से खाता है? साइन इन करें',
        'login_subtitle': 'वापस स्वागत है, जारी रखने के लिए अपनी जानकारी दर्ज करें।',
        'signup_subtitle': 'शिकायतों की रिपोर्ट और ट्रैकिंग के लिए नागरिक प्रोफ़ाइल बनाएं।',
        'full_name': 'पूरा नाम',
        'full_name_hint': 'अपना आधिकारिक नाम दर्ज करें',
        'phone_number': 'मोबाइल नंबर',
        'phone_hint': '10 अंकों का मोबाइल नंबर दर्ज करें',
        'email': 'ईमेल पता',
        'email_hint': 'अपना ईमेल पता दर्ज करें',
        'password': 'पासवर्ड',
        'password_hint': 'अपना पासवर्ड दर्ज करें',
        'confirm_password': 'पासवर्ड की पुष्टि करें',
        'district': 'जिला / नगर निगम',
        'district_hint': 'उदा., सोलापुर नगर निगम',
        'ward': 'वार्ड / जोन संख्या',
        'ward_hint': 'उदा., वार्ड 14',
        'remember_me': 'मुझे याद रखें',
        'forgot_password': 'पासवर्ड भूल गए?',
        'or_continue_with': 'या इसके साथ जारी रखें',
        'dont_have_account': 'खाता नहीं है?',
        'create_account': 'नागरिक खाता बनाएं',
        'login_to_account': 'अपने खाते में साइन इन करें',
        'logging_in': 'साइन इन हो रहा है...',
        'creating_account': 'नागरिक खाता बन रहा है...',
        'login_success': 'सफलतापूर्वक साइन इन किया गया!',
        'signup_success': 'नागरिक खाता सफलतापूर्वक बनाया गया!',
        'invalid_credentials': 'अमान्य विवरण। कृपया ईमेल और पासवर्ड की जांच करें।',
        'fill_required_fields': 'कृपया सभी आवश्यक फ़ील्ड भरें।',
        'logout': 'लॉग आउट',
        'logout_confirm': 'क्या आप वाकई लॉग आउट करना चाहते हैं?',

        // Navigation & Menu
        'nav_home': 'होम',
        'nav_report': 'रिपोर्ट',
        'nav_track': 'ट्रैक',
        'nav_map': 'नक्शा',
        'nav_profile': 'प्रोफ़ाइल',
        'menu': 'मेनू',
        'home_dashboard': 'मुख्य डैशबोर्ड',
        'track_complaints': 'शिकायतें ट्रैक करें',
        'nearby_issues_map': 'नजदीकी समस्याओं का नक्शा',
        'local_civic_feed': 'स्थानीय नागरिक फीड',
        'emergency_helpline': 'आपातकालीन हेल्पलाइन',
        'change_language': 'भाषा बदलें',
        'notifications': 'सूचनाएं',
        'settings': 'सेटिंग्स',
        'help_support': 'सहायता और समर्थन',

        // Dashboard
        'good_morning': 'शुभ प्रभात',
        'good_afternoon': 'शुभ दोपहर',
        'good_evening': 'शुभ संध्या',
        'report_problem_title': 'नगर निगम समस्या की रिपोर्ट करें',
        'report_problem_subtitle': 'सड़क, पानी, स्ट्रीट लाइट, कचरा व स्वच्छता',
        'register_new_grievance': 'नई शिकायत दर्ज करें',
        'citizen_services': 'नागरिक सेवाएं',
        'discover_support': 'खोजें और समर्थन करें',
        'map_view': 'मानचित्र दृश्य',
        'live_status_timeline': 'रीयल-टाइम स्थिति',
        'control_room_police': 'नियंत्रण कक्ष और पुलिस',
        'recent_grievances': 'हाल की शिकायतें',
        'view_all': 'सभी देखें',
        'no_reports_yet': 'अभी तक कोई शिकायत दर्ज नहीं की गई',
        'no_reports_desc': 'अपने क्षेत्र को बेहतर बनाने के लिए पहली शिकायत दर्ज करें।',
        'refresh_location': 'स्थान ताज़ा करें',
        'my_reports': 'मेरी शिकायतें',
        'community_reports': 'समुदाय की शिकायतें',

        // Grievance Reporting Step Flow
        'select_category_step': 'चरण १/३: श्रेणी चुनें',
        'select_issue_category': 'समस्या की श्रेणी चुनें',
        'category_guide': 'अपने क्षेत्र की समस्या से संबंधित नगर निगम विभाग का चयन करें।',
        'municipal_departments': 'नगर निगम विभाग',
        'provide_details_step': 'चरण २/३: विवरण दें',
        'review_submit_step': 'चरण ३/३: समीक्षा और जमा करें',
        'selected_category': 'चुनी गई श्रेणी',
        'complaint_description': 'शिकायत का विवरण *',
        'complaint_desc_hint': 'समस्या का स्पष्ट विवरण दें (जैसे गंभीरता, लैंडमार्क, अवधि)...',
        'photo_evidence': 'फोटो साक्ष्य *',
        'upload_photos_max': 'फोटो जोड़ें (अधिकतम ५)',
        'take_photo': 'फोटो खींचें',
        'choose_from_gallery': 'गैलरी से चुनें',
        'problem_location': 'समस्या का स्थान *',
        'use_current_location': 'वर्तमान स्थान उपयोग करें',
        'enter_address_hint': 'पता या नजदीकी लैंडमार्क दर्ज करें...',
        'priority': 'प्राथमिकता',
        'priority_high': 'उच्च',
        'priority_medium': 'मध्यम',
        'priority_low': 'निम्न',
        'priority_critical': 'अतिगंभीर',
        'priority_high_desc': 'तत्काल खतरा / त्वरित समाधान',
        'priority_medium_desc': 'मानक सेवा अनुरोध',
        'priority_low_desc': 'नियमित रखरखाव',
        'continue_to_review': 'समीक्षा के लिए आगे बढ़ें',
        'submit_complaint': 'शिकायत दर्ज करें',
        'submitting_complaint': 'शिकायत दर्ज की जा रही है...',
        'complaint_submitted': 'शिकायत सफलतापूर्वक दर्ज की गई',
        'complaint_submitted_desc': 'आपकी शिकायत प्राप्त हो चुकी है और संबंधित विभाग को भेज दी गई है।',
        'complaint_ref_id': 'शिकायत संदर्भ संख्या',
        'green_credits_earned': 'सक्रिय नागरिक रिपोर्टिंग के लिए +10 ग्रीन क्रेडिट्स अर्जित!',
        'what_happens_next': 'आगे क्या होगा?',
        'next_step_1': 'स्वचालित नगर निगम सत्यापन एवं विभाग आवंटन।',
        'next_step_2': 'फील्ड निरीक्षण टीम स्थल पर भेजी जाएगी।',
        'next_step_3': '"ट्रैक करें" में रीयल-टाइम प्रगति और फोटो देखें।',
        'track_complaint': 'शिकायत ट्रैक करें',
        'return_to_home': 'मुख्य पृष्ठ पर लौटें',

        // Categories & Descriptions
        'cat_potholes_roads': 'सड़क और गड्ढे',
        'cat_potholes_roads_desc': 'गड्ढे, टूटी सड़कें, क्षतिग्रस्त फुटपाथ',
        'cat_water_drainage': 'जलापूर्ति एवं लीकेज',
        'cat_water_drainage_desc': 'पाइप लीकेज, कम दबाव, गंदा पानी',
        'cat_drainage_sewage': 'ड्रेनेज और सीवरेज',
        'cat_drainage_sewage_desc': 'बंद नालियां, खुले मैनहोल, सीवर ओवरफ्लो',
        'cat_electricity_streetlights': 'बिजली व स्ट्रीट लाइट',
        'cat_electricity_streetlights_desc': 'खराब स्ट्रीट लाइट, लटकते तार, बिजली गुल',
        'cat_waste_management': 'कचरा एवं स्वच्छता',
        'cat_waste_management_desc': 'कचरे का ढेर, डस्टबिन ओवरफ्लो, गंदगी',
        'cat_safety_hazard': 'सार्वजनिक सुरक्षा खतरे',
        'cat_safety_hazard_desc': 'खतरनाक इमारतें, खुले गड्ढे, आग का खतरा',
        'cat_parks_trees': 'पार्क एवं गिरे हुए पेड़',
        'cat_parks_trees_desc': 'गिरे हुए पेड़, टूटी डालियां, पार्क रखरखाव',
        'cat_illegal_encroachment': 'अवैध अतिक्रमण',
        'cat_illegal_encroachment_desc': 'फुटपाथ जाम, अनधिकृत निर्माण',
        'cat_other': 'अन्य शिकायत',
        'cat_other_desc': 'सामान्य नागरिक समस्याएं',

        // Tracking & Status Lifecycle
        'tracking_title': 'शिकायतों की स्थिति',
        'all_reports': 'सभी रिपोर्ट',
        'active_reports': 'सक्रिय',
        'resolved_reports': 'हल की गई',
        'status_submitted': 'जमा किया गया',
        'status_under_review': 'समीक्षाधीन',
        'status_assigned': 'अधिकारी नियुक्त',
        'status_in_progress': 'कार्य प्रगति पर',
        'status_resolution_submitted': 'समाधान प्रस्तुत',
        'status_citizen_verification': 'नागरिक सत्यापन',
        'status_resolved': 'हल हो गया',
        'status_verified': 'सत्यापित',
        'status_closed': 'बंद',
        'status_reopened': 'पुनः खोला गया',
        'status_rejected': 'अस्वीकृत',
        'assigned_officer': 'नियुक्त अधिकारी',
        'field_team': 'फील्ड टीम',
        'expected_resolution': 'अपेक्षित समाधान समय (SLA)',
        'hours': 'घंटे',
        'days': 'दिन',
        'verify_resolution': 'समाधान सत्यापित करें',
        'confirm_resolved': 'हाँ, समस्या हल हो गई',
        'not_resolved_reopen': 'अभी भी हल नहीं हुआ (पुनः खोलें)',
        'resolution_notes': 'अधिकारी समाधान विवरण',
        'resolution_evidence': 'कार्य समाधान फोटो साक्ष्य',

        // Civic Feed & Community Map
        'civic_feed_title': 'स्थानीय नागरिक फीड',
        'nearby_issues': 'नजदीकी नागरिक समस्याएं',
        'support_issue': 'समर्थन दें',
        'supported': 'समर्थित',
        'upvotes': 'समर्थक',
        'filter_all': 'सभी',
        'filter_nearby': 'नजदीकी (२ किमी)',
        'filter_trending': 'सर्वाधिक समर्थित',
        'distance_away': 'दूर',
        'map_layers': 'नक्शा लेयर्स',
        'legend': 'संकेत सूची',

        // Profile & Credits
        'my_profile': 'मेरी प्रोफ़ाइल',
        'edit_profile': 'प्रोफ़ाइल संपादित करें',
        'green_points': 'नागरिक ग्रीन पॉइंट्स',
        'total_reports': 'कुल रिपोर्ट',
        'resolved_count': 'हल हुए',
        'in_progress_count': 'प्रगति में',
        'account_settings': 'खाता सेटिंग्स',
        'privacy_policy': 'गोपनीयता नीति',
        'terms_of_service': 'सेवा की शर्तें',

        // Emergency Helpline
        'emergency_contacts': 'आपातकालीन हेल्पलाइन नंबर',
        'ambulance': 'एम्बुलेंस (चिकित्सा)',
        'fire_brigade': 'दमकल विभाग (अग्निशामक)',
        'police_control': 'पुलिस नियंत्रण कक्ष',
        'municipal_helpline': 'नगर निगम 24x7 हेल्पलाइन',
        'disaster_mgmt': 'आपदा प्रबंधन प्रकोष्ठ',

        // System, Feedback, Errors & Permissions
        'loading': 'लोड हो रहा है...',
        'please_wait': 'कृपया प्रतीक्षा करें...',
        'network_error': 'नेटवर्क त्रुटि। कृपया पुनः प्रयास करें।',
        'location_error': 'स्थान अनुपलब्ध। कृपया GPS सक्षम करें।',
        'permission_required': 'अनुमति आवश्यक',
        'camera_permission_msg': 'फोटो साक्ष्य जोड़ने के लिए कैमरा और स्टोरेज अनुमति आवश्यक है।',
        'success': 'सफल',
        'error': 'त्रुटि',
        'retry': 'पुनः प्रयास करें',
        'cancel': 'रद्द करें',
        'confirm': 'पुष्टि करें',
        'close': 'बंद करें',
        'language_settings': 'भाषा सेटिंग्स',
        'choose_language': 'अपनी भाषा चुनें',
        'language_changed_to': 'भाषा बदलकर की गई',

        // Additional Auth & Login Keys in Hindi
        'app_tagline_login': 'सशक्त समुदाय, हर एक रिपोर्ट के साथ।',
        'citizen_tab': 'नागरिक',
        'field_officer_tab': 'फील्ड अधिकारी',
        'sign_in_tab': 'साइन इन (आधार/OTP)',
        'sign_up_tab': 'नया नागरिक पंजीकरण',
        'citizen_login_header': 'नागरिक लॉगिन',
        'field_officer_login_header': 'फील्ड अधिकारी / कंत्राटदार लॉगिन',
        'create_account_header': 'नागरिक खाता बनाएं',
        'join_municipal_desc': 'सत्यापित नागरिक योगदानकर्ता के रूप में अपने नगर क्षेत्र से जुड़ें (स्कोर 0 • 🌱 सिविक स्टार्टर)',
        'full_legal_name_hint': 'पूरा आधिकारिक नाम (उदा. विक्रम पाटिल)',
        'mobile_number_hint': '10 अंकों का मोबाइल नंबर',
        'email_address_hint': 'ईमेल पता (उदा. name@example.com)',
        'password_char_hint': 'पासवर्ड (न्यूनतम 6 अक्षर)',
        'district_city_hint': 'जिला / शहर',
        'ward_area_hint': 'वार्ड / क्षेत्र',
        'register_enter_btn': 'पंजीकरण करें और पोर्टल में प्रवेश करें',
        'aadhaar_input_hint': '12 अंकों का आधार नंबर',
        'login_with_aadhaar_btn': 'आधार से लॉगिन करें',
        'otp_sent_card_title': 'आपके मोबाइल पर OTP भेजा गया',
        'otp_input_hint': '6 अंकों का OTP (उदा. 123456)',
        'resend_otp_in_text': 'OTP पुनः भेजें',
        'can_resend_otp_text': 'आप अब OTP पुनः भेज सकते हैं',
        'resend_btn': 'पुनः भेजें',
        'verify_login_btn': 'सत्यापित करें और लॉगिन करें',
        'change_aadhaar_btn': 'आधार नंबर बदलें',
        'officer_id_hint': 'अधिकारी आईडी / ईमेल (उदा. demo.officer@civicresolve.gov)',
        'login_as_officer_btn': 'फील्ड अधिकारी के रूप में लॉगिन करें',
        'evaluator_access_title': 'परीक्षक त्वरित प्रवेश',
        'evaluator_access_desc': 'हैकथॉन मूल्यांकन और लाइव परीक्षण के लिए एक-टैप नागरिक सत्र।',
        'evaluator_access_citizen_desc': 'हैकथॉन मूल्यांकन और लाइव परीक्षण के लिए एक-टैप नागरिक सत्र।',
        'evaluator_access_officer_desc': 'नगर निगम फील्ड कार्यकर्ता मूल्यांकन और लाइव कार्य ट्रैकिंग के लिए एक-टैप फील्ड अधिकारी सत्र।',
        'one_tap_demo_btn': '⚡ वन-टैप परीक्षक / डेमो लॉगिन',
        'one_tap_citizen_demo_btn': '⚡ वन-टैप नागरिक डेमो लॉगिन',
        'one_tap_officer_demo_btn': '⚡ वन-टैप फील्ड अधिकारी डेमो लॉगिन',

        // Additional Track Keys in Hindi
        'track_my_complaints': 'मेरी शिकायतें ट्रैक करें',
        'realtime_action_status': 'रीयल-टाइम नगर निगम निवारण स्थिति',
        'search_complaints_hint': 'आईडी (#CR-...), शीर्षक, स्थान से खोजें...',
        'syncing_status': 'नगर निगम प्रणाली से लाइव स्थिति सिंक हो रही है...',
        'complaints_found': 'शिकायतें मिलीं',
        'live_sync': 'लाइव सिंक',
        'no_matching_complaints': 'कोई मेल खाती शिकायत नहीं मिली',
        'no_complaints_yet_track': 'अभी तक कोई शिकायत नहीं',
        'try_changing_filters': 'कृपया खोज कीवर्ड या फ़िल्टर चयन बदल कर देखें।',
        'report_first_track_desc': 'अपनी पहली नागरिक समस्या की रिपोर्ट करें और यहां समाधान ट्रैक करें।',
        'clear_filters': 'फ़िल्टर हटाएं',
        'report_first_issue_btn': 'अपनी पहली समस्या दर्ज करें',
        'sort_newest': 'नवीनतम',
        'sort_oldest': 'पुरातन',
        'filter_submitted': 'जमा किया गया',
        'filter_under_review': 'समीक्षाधीन',
        'filter_assigned': 'अधिकारी नियुक्त',
        'filter_in_progress': 'कार्य प्रगति पर',
        'filter_resolved': 'निवारण हुआ',
        'filter_high_priority': 'उच्च प्राथमिकता',

        // Additional Feed & Map Keys in Hindi
        'gps_off_showing_public': 'GPS बंद: सार्वजनिक शिकायतें प्रदर्शित',
        'enable_gps': 'GPS सक्षम करें',
        'city_wide': 'शहर स्तर पर',
        'km_radius': 'किमी दायरा',
        'sort_most_supported': 'सर्वाधिक समर्थित',
        'sort_recent': 'हाल के',
        'sort_nearby': 'नजदीक',
        'search_feed_hint': 'शीर्षक, स्थान या विवरण द्वारा खोजें...',
        'supported_issue_award': 'समस्या का समर्थन किया! +2 नागरिक प्रभाव अंक मिले।',
        'live_nearby_issues': 'आसपास की नागरिक समस्याएं',
        'gis_reports_near_you': 'आपके नजदीकी रीयल-टाइम नगर निगम जीआईएस रिपोर्ट',
        'gps_unavailable_center': 'GPS अनुपलब्ध। नगर केंद्र प्रदर्शित हो रहा है।',
        'map_centered_gps': 'मानचित्र आपके वर्तमान GPS स्थान पर केंद्रित है।',
        'submit_feedback_comments': 'कृपया प्रतिक्रिया टिप्पणी दर्ज करें।',
        'feedback_recorded': 'धन्यवाद! आपकी प्रतिक्रिया दर्ज कर ली गई है।',
        'enter_feedback_hint': 'प्रतिक्रिया विवरण दर्ज करें...',
        'rate_experience': 'समाधान गुणवत्ता का मूल्यांकन करें',
        'submit_feedback': 'प्रतिक्रिया जमा करें',

        // Profile & Account Keys in Hindi
        'verified_citizen': 'सत्यापित नागरिक',
        'personal_info': 'व्यक्तिगत जानकारी',
        'date_of_birth': 'जन्म तिथि',
        'occupation': 'व्यवसाय',
        'member_since': 'सदस्यता तिथि',
        'contact_info': 'संपर्क विवरण',
        'address': 'पता',
        'community_activity': 'सामुदायिक गतिविधि',
        'reports_submitted_count': 'दर्ज शिकायतें',
        'community_score': 'सामुदायिक स्कोर',
        'green_credits_label': 'ग्रीन क्रेडिट्स',
        'civic_rewards_contributions': 'नागरिक पुरस्कार और योगदान',
        'scores_auto_updated_desc': 'जब नगर निगम टीम द्वारा शिकायतों या समाधानों का सत्यापन किया जाता है, तब स्कोर स्वतः अपडेट होते हैं।',
        'view_contribution_history_btn': 'योगदान इतिहास देखें',
        'plant_shop_btn': 'पौधा केंद्र (प्लांट शॉप)',
        'edit_profile_btn': 'प्रोफ़ाइल संपादित करें',
        'save_changes_btn': 'परिवर्तन सहेजें',
        'profile_updated_toast': 'प्रोफ़ाइल सफलतापूर्वक अपडेट की गई',

        // Emergency Contacts Keys in Hindi
        'police_emergency': 'पुलिस आपातकालीन',
        'police_emergency_desc': 'त्वरित पुलिस सहायता और अपराध रिपोर्टिंग के लिए',
        'medical_emergency': 'चिकित्सा आपातकालीन',
        'medical_emergency_desc': 'एम्बुलेंस और आपातकालीन चिकित्सा सेवाएं',
        'fire_brigade_desc': 'अग्निशमन और बचाव अभियान',
        'disaster_mgmt_desc': 'प्राकृतिक आपदा और आपातकालीन प्रबंधन',
        'women_helpline': 'महिला हेल्पलाइन',
        'women_helpline_desc': 'मुसीबत में महिलाओं के लिए आपातकालीन सहायता',
        'child_helpline': 'चाइल्ड हेल्पलाइन',
        'child_helpline_desc': 'जरूरतमंद बच्चों के लिए आपातकालीन सहायता',
        'tourist_emergency': 'पर्यटक आपातकालीन',
        'tourist_emergency_desc': 'पर्यटक सहायता और आपातकालीन सेवा',
        'senior_helpline': 'वरिष्ठ नागरिक हेल्पलाइन',
        'senior_helpline_desc': 'वरिष्ठ नागरिकों के लिए आपातकालीन सहायता',
        'confirm_call': 'कॉल की पुष्टि करें',
        'are_you_sure_call': 'क्या आप वाकई कॉल करना चाहते हैं?',
        'call_now': 'अभी कॉल करें',
        'connecting_to': 'कनेक्ट किया जा रहा है',
        'emergency_tips': 'आपातकालीन सुझाव',
        'stay_calm': 'शांत रहें',
        'stay_calm_desc': 'आपातकालीन सेवाओं को कॉल करते समय शांत रहें और स्पष्ट रूप से बोलें',
        'know_location': 'अपना स्थान जानें',
        'know_location_desc': 'अपना सटीक स्थान या पास का लैंडमार्क बताने के लिए तैयार रहें',
        'have_info_ready': 'महत्वपूर्ण जानकारी तैयार रखें',
        'have_info_ready_desc': 'चिकित्सा जानकारी और आपातकालीन संपर्क सुलभ रखें',
        'follow_instructions': 'निर्देशों का पालन करें',
        'follow_instructions_desc': 'ध्यान से सुनें और ऑपरेटर के निर्देशों का पालन करें',
        'dont_hang_up': 'कॉल न काटें',
        'dont_hang_up_desc': 'जब तक ऑपरेटर न कहे, लाइन पर बने रहें',

        // Help & Support Keys in Hindi
        'were_here_to_help': 'हम आपकी सहायता के लिए हैं',
        'help_intro_desc': 'उत्तर खोजें, ऐप का उपयोग करना सीखें और हमारी सहायता टीम से संपर्क करें',
        'app_guide_tab': 'ऐप गाइड',
        'faq_tab': 'अक्सर पूछे जाने वाले प्रश्न',
        'contact_tab': 'संपर्क करें',
        'getting_started': 'शुरुआत कैसे करें',
        'step_create_profile': '१. अपनी प्रोफ़ाइल बनाएं',
        'step_create_profile_desc': 'बुनियादी जानकारी के साथ अपना खाता सेट करें',
        'step_enable_location': '२. स्थान सेवाएं सक्षम करें',
        'step_enable_location_desc': 'सटीक रिपोर्टिंग के लिए लोकेशन की अनुमति दें',
        'step_report_issue': '३. समस्या की रिपोर्ट करें',
        'step_report_issue_desc': 'फोटो लें, श्रेणी चुनें और शिकायत दर्ज करें',
        'step_track_progress': '४. प्रगति ट्रैक करें',
        'step_track_progress_desc': 'रीयल-टाइम स्थिति और अधिकारी असाइनमेंट देखें',
        'step_verify_resolution': '५. समाधान का सत्यापन करें',
        'step_verify_resolution_desc': 'किए गए कार्य की पुष्टि करें और नागरिक प्रभाव अंक अर्जित करें',

        // Notification Keys in Hindi
        'clear_all_notifications': 'सभी सूचनाएं हटाएं',
        'clear_all_confirm_desc': 'क्या आप वाकई सभी सूचनाएं हटाना चाहते हैं? यह क्रिया पूर्ववत नहीं की जा सकती।',
        'all_notifications_cleared': 'सभी सूचनाएं हटा दी गईं',
        'no_notifications_yet': 'अभी कोई सूचना नहीं है',
        'all_caught_up': 'सब अद्यतन है! आपकी शिकायतों के अपडेट यहां दिखाई देंगे।',

        // Map View Keys in Hindi
        'map_view_title': 'आसपास की नागरिक समस्याएं',
        'map_view_subtitle': 'आपके नजदीक रीयल-टाइम नगर निगम जीआईएस रिपोर्ट',
        'category_all': 'सभी',
        'category_roads': 'सड़कें',
        'category_water': 'पानी',
        'category_electricity': 'बिजली',
        'category_sanitation': 'स्वच्छता',
        'category_safety': 'सुरक्षा',
        'status_active': 'सक्रिय',
        'status_all': 'सभी',
        'view_as_map': 'मानचित्र दृश्य',
        'view_as_list': 'सूची दृश्य',
        'recenter_map': 'पुनः केंद्रित करें',

        // Common Form & Dialog Actions in Hindi
        'edit': 'संपादित करें',
        'camera': 'कैमरा',
        'gallery': 'गैलरी',
        'select_location': 'स्थान चुनें',
        'confirm_location': 'स्थान की पुष्टि करें',
        'location_confirmed': 'स्थान की पुष्टि हुई!',
        'quick_options': 'त्वरित विकल्प',
        'specific_address_label': 'विशिष्ट पता या लैंडमार्क *',
        'fill_address': 'कृपया समस्या का पता प्रदान करें',
        'fill_specific_address': 'कृपया अधिक विशिष्ट पता दें',
        'fill_description': 'कृपया समस्या का विवरण दें',
        'fill_detailed_description': 'कृपया अधिक विस्तृत विवरण दें (कम से कम 10 वर्ण)',
        'suggested_priority': 'सुझाई गई प्राथमिकता',
        'ai_review_disclaimer': 'एआई सुझावों की नगर निगम कर्मचारियों द्वारा समीक्षा की जा सकती है।',
        'gps_unavailable_fallback': 'डिफ़ॉल्ट नगर निगम केंद्र का उपयोग कर रहे हैं (जीपीएस अनुपलब्ध)। सटीक स्थान सेट करने के लिए नक्शा खींचें या पता संपादित करें।',
        'attached_evidence': 'संलग्न साक्ष्य',
        'no_images_attached': 'कोई फोटो संलग्न नहीं है।',
        'replace_photo_to_submit': 'जमा करने के लिए फोटो बदलें',
        'genuine_report_disclaimer': 'जमा करके, आप पुष्टि करते हैं कि यह रिपोर्ट एक वास्तविक नागरिक समस्या का वर्णन करती है।',
        'official_municipal_tracking': 'आधिकारिक नगर निगम ट्रैकिंग',
        'seven_stage_lifecycle': '७-चरणीय नगर निगम जीवनचक्र',
        'stage_1_title': '१. शिकायत दर्ज की गई',
        'stage_1_desc': 'CivicResolve नगर निगम शिकायत प्रणाली में पंजीकृत।',
        'stage_2_title': '२. समीक्षाधीन',
        'stage_2_desc': 'नगर निगम प्रकोष्ठ क्षेत्राधिकार और प्राथमिकता का आकलन कर रहा है।',
        'stage_3_title': '३. विभाग और फील्ड अधिकारी को आवंटित',
        'stage_3_desc': 'संबंधित नगर निगम रखरखाव प्रभाग को सौंपा गया।',
        'stage_4_title': '४. फील्ड कार्य प्रगति पर है',
        'stage_4_desc': 'फील्ड निरीक्षण और रखरखाव दल स्थल पर सक्रिय है।',
        'stage_5_title': '५. समाधान प्रस्तुत किया गया',
        'stage_5_desc': 'फील्ड ठेकेदार ने काम का फोटो साक्ष्य अपलोड किया है।',
        'stage_6_title': '६. समाधान सत्यापन',
        'stage_6_desc': 'साक्ष्य सत्यापन और नागरिक संतुष्टि समीक्षा।',
        'stage_7_title': '७. वैधानिक समापन',
        'stage_7_desc': 'समस्या का सफलतापूर्वक समाधान हुआ और नगर निगम द्वारा अनुमोदित।',
        'submitted_location': 'शिकायत दर्ज स्थान',
        'awaiting_field_assignment': 'फील्ड आवंटन की प्रतीक्षा है',
        'on_site_active': 'स्थल पर सक्रिय',
        'assigned_dispatched': 'आवंटित / रवाना किया गया',
        'remediation_submitted': 'समाधान साक्ष्य प्रस्तुत',
        'officer_location_unavailable': 'अधिकारी का स्थान अनुपलब्ध',
        'jurisdictional_cell_assessing': 'संबंधित नगर निगम सेल आकलन कर रहा है',
      },

      // =======================================================================
      // MARATHI (मराठी)
      // =======================================================================
      'mr': {
        // App Identity & Headers
        'app_name': 'CivicResolve',
        'app_slogan': 'चांगले समुदाय एकत्र बनवतात',
        'app_tagline': 'महानगरपालिका नागरिक तक्रार निवारण पोर्टल',
        'welcome_to_civicresolve': 'CivicResolve मध्ये आपले स्वागत आहे',
        'welcome_subtitle': 'नागरी समस्यांची तक्रार नोंदवा, थेट निवारण ट्रॅक करा आणि आपले शहर अधिक स्वच्छ व सुरक्षित बनवा.',
        'municipal_citizen_services': 'महानगरपालिका नागरिक सेवा',
        'municipal_admin_control': 'महानगरपालिका प्रशासकीय नियंत्रण',
        'official_civic_service': 'अधिकृत नागरी निवारण सेवा • जन तक्रार निवारण कक्ष',

        // Authentication & Roles
        'citizen': 'नागरिक',
        'public_servant': 'शासकीय अधिकारी / क्षेत्रीय पथक',
        'role_citizen_desc': 'नागरी समस्या नोंदवा आणि परिसरातील प्रगती ट्रॅक करा',
        'role_officer_desc': 'महानगरपालिका अधिकारी आणि क्षेत्रीय कर्मचारी लॉगिन',
        'log_in': 'लॉग इन',
        'sign_up': 'साइन अप',
        'sign_in': 'साइन इन करा',
        'new_citizen_register': 'नवीन नागरिक? येथे नोंदणी करा',
        'already_have_account': 'आधीच खाते आहे? साइन इन करा',
        'login_subtitle': 'स्वागत आहे, पुढे जाण्यासाठी आपले तपशील प्रविष्ट करा.',
        'signup_subtitle': 'तक्रार नोंदणी आणि ट्रॅकिंगसाठी नागरिक प्रोफाइल तयार करा.',
        'full_name': 'पूर्ण नाव',
        'full_name_hint': 'आपले अधिकृत नाव प्रविष्ट करा',
        'phone_number': 'मोबाईल नंबर',
        'phone_hint': '१० अंकी मोबाईल नंबर प्रविष्ट करा',
        'email': 'ईमेल पत्ता',
        'email_hint': 'आपला ईमेल पत्ता प्रविष्ट करा',
        'password': 'पासवर्ड',
        'password_hint': 'आपला पासवर्ड प्रविष्ट करा',
        'confirm_password': 'पासवर्डची पुष्टी करा',
        'district': 'जिल्हा / महानगरपालिका',
        'district_hint': 'उदा., सोलापूर महानगरपालिका',
        'ward': 'प्रभाग / वॉर्ड क्र.',
        'ward_hint': 'उदा., प्रभाग १४',
        'remember_me': 'मला लक्षात ठेवा',
        'forgot_password': 'पासवर्ड विसरलात?',
        'or_continue_with': 'किंवा पुढे चला',
        'dont_have_account': 'खाते नाही?',
        'create_account': 'नागरिक खाते तयार करा',
        'login_to_account': 'आपल्या खात्यात साइन इन करा',
        'logging_in': 'साइन इन होत आहे...',
        'creating_account': 'नागरिक खाते तयार होत आहे...',
        'login_success': 'यशस्वीरित्या साइन इन झाले!',
        'signup_success': 'नागरिक खाते यशस्वीरित्या तयार झाले!',
        'invalid_credentials': 'अमान्य तपशील. कृपया ईमेल व पासवर्ड तपासा.',
        'fill_required_fields': 'कृपया सर्व आवश्यक माहिती भरा.',
        'logout': 'लॉग आउट',
        'logout_confirm': 'आपली खात्री आहे की आपण लॉग आउट करू इच्छिता?',

        // Navigation & Menu
        'nav_home': 'मुख्यपृष्ठ',
        'nav_report': 'तक्रार',
        'nav_track': 'ट्रॅक',
        'nav_map': 'नकाशा',
        'nav_profile': 'प्रोफाइल',
        'menu': 'मेनू',
        'home_dashboard': 'मुख्य डॅशबोर्ड',
        'track_complaints': 'तक्रारी ट्रॅक करा',
        'nearby_issues_map': 'जवळील समस्यांचा नकाशा',
        'local_civic_feed': 'स्थानिक नागरी फीड',
        'emergency_helpline': 'आपत्कालीन हेल्पलाईन',
        'change_language': 'भाषा बदला',
        'notifications': 'सूचना',
        'settings': 'सेटिंग्ज',
        'help_support': 'मदत आणि सहाय्य',

        // Dashboard
        'good_morning': 'शुभ प्रभात',
        'good_afternoon': 'शुभ दुपार',
        'good_evening': 'शुभ संध्याकाळ',
        'report_problem_title': 'महानगरपालिका समस्या नोंदवा',
        'report_problem_subtitle': 'खड्डे, पाणीपुरवठा, पथदिवे, कचरा व स्वच्छता',
        'register_new_grievance': 'नवीन तक्रार दाखल करा',
        'citizen_services': 'नागरी सेवा',
        'discover_support': 'शोधा आणि पाठिंबा द्या',
        'map_view': 'नकाशा दृश्य',
        'live_status_timeline': 'थेट स्थिती',
        'control_room_police': 'नियंत्रण कक्ष आणि पोलीस',
        'recent_grievances': 'अलीकडील तक्रारी',
        'view_all': 'सर्व पहा',
        'no_reports_yet': 'अद्याप कोणतीही तक्रार नोंदवलेली नाही',
        'no_reports_desc': 'आपला परिसर सुधारण्यासाठी पहिली तक्रार नोंदवा.',
        'refresh_location': 'स्थान रिफ्रेश करा',
        'my_reports': 'माझ्या तक्रारी',
        'community_reports': 'परिसरातील तक्रारी',

        // Grievance Reporting Step Flow
        'select_category_step': 'टप्पा १/३: वर्ग निवडा',
        'select_issue_category': 'समस्येचा वर्ग निवडा',
        'category_guide': 'आपल्या भागातील समस्येशी जुळणारा महानगरपालिका विभाग निवडा.',
        'municipal_departments': 'महानगरपालिका विभाग',
        'provide_details_step': 'टप्पा २/३: तपशील द्या',
        'review_submit_step': 'टप्पा ३/३: पुनरावलोकन व सादर करा',
        'selected_category': 'निवडलेला वर्ग',
        'complaint_description': 'तक्रारीचे वर्णन *',
        'complaint_desc_hint': 'समस्येचे स्पष्ट वर्णन करा (तीव्रता, जवळील खूण, कालावधी)...',
        'photo_evidence': 'फोटो पुरावा *',
        'upload_photos_max': 'फोटो जोडा (कमाल ५)',
        'take_photo': 'फोटो काढा',
        'choose_from_gallery': 'गॅलरीतून निवडा',
        'problem_location': 'समस्येचे ठिकाण *',
        'use_current_location': 'सध्याचे स्थान वापरा',
        'enter_address_hint': 'पत्ता किंवा जवळची खूण टाका (उदा. सिटी हॉस्पिटल गेट २ जवळ)...',
        'priority': 'प्राधान्यक्रम',
        'priority_high': 'उच्च',
        'priority_medium': 'मध्यम',
        'priority_low': 'सामान्य',
        'priority_critical': 'अतिगंभीर',
        'priority_high_desc': 'तातडीचा धोका / त्वरित निवारण',
        'priority_medium_desc': 'नियमित सेवा विनंती',
        'priority_low_desc': 'सामान्य देखभाल',
        'continue_to_review': 'पुढील पुनरावलोकन करा',
        'submit_complaint': 'तक्रार दाखल करा',
        'submitting_complaint': 'तक्रार दाखल केली जात आहे...',
        'complaint_submitted': 'तक्रार यशस्वीरित्या नोंदवली',
        'complaint_submitted_desc': 'आपली तक्रार नोंदवली गेली असून संबंधित विभागाकडे सोपवली आहे.',
        'complaint_ref_id': 'तक्रार संदर्भ क्रमांक',
        'green_credits_earned': 'सक्रिय नागरी तक्रारीसाठी +१० ग्रीन क्रेडिट्स मिळाले!',
        'what_happens_next': 'पुढे काय होणार?',
        'next_step_1': 'स्वयंचलित महानगरपालिका पडताळणी आणि विभाग वाटप.',
        'next_step_2': 'क्षेत्रीय तपासणी पथक घटनास्थळी पाठवले जाईल.',
        'next_step_3': '"तक्रारी ट्रॅक करा" मध्ये थेट प्रगती व फोटो पहा.',
        'track_complaint': 'तक्रार ट्रॅक करा',
        'return_to_home': 'मुख्यपृष्ठावर परत जा',

        // Categories & Descriptions
        'cat_potholes_roads': 'रस्ते आणि खड्डे',
        'cat_potholes_roads_desc': 'खड्डे, खराब रस्ते, उखडलेले डांबर, तुटलेले पदपथ',
        'cat_water_drainage': 'पाणीपुरवठा व गळती',
        'cat_water_drainage_desc': 'पाईप गळती, कमी दाब, दूषित पाणी',
        'cat_drainage_sewage': 'ड्रेनेज आणि सांडपाणी',
        'cat_drainage_sewage_desc': 'तुंबलेली गटारे, उघडे मॅनहोल, सांडपाणी वाहणे',
        'cat_electricity_streetlights': 'विद्युत व पथदिवे',
        'cat_electricity_streetlights_desc': 'बंद पथदिवे, तुटलेल्या तारा, वीज पुरवठा खंडित',
        'cat_waste_management': 'कचरा व स्वच्छता',
        'cat_waste_management_desc': 'कचऱ्याचा ढीग, कचराकुंडी ओसंडणे, दुर्गंधी',
        'cat_safety_hazard': 'सार्वजनिक सुरक्षितता धोके',
        'cat_safety_hazard_desc': 'धोकादायक इमारती, उघडे खड्डे, आगीचा धोका',
        'cat_parks_trees': 'उद्याने व पडलेली झाडे',
        'cat_parks_trees_desc': 'पडलेली झाडे, फांद्या तोडणे, बागेची देखभाल',
        'cat_illegal_encroachment': 'बेकायदेशीर अतिक्रमण',
        'cat_illegal_encroachment_desc': 'पदपथ अडवणे, अनधिकृत बांधकाम',
        'cat_other': 'इतर तक्रारी',
        'cat_other_desc': 'सर्वसाधारण नागरी समस्या',

        // Tracking & Status Lifecycle
        'tracking_title': 'तक्रारींची स्थिती',
        'all_reports': 'सर्व तक्रारी',
        'active_reports': 'सक्रिय',
        'resolved_reports': 'सुटलेल्या',
        'status_submitted': 'नोंदवले',
        'status_under_review': 'पुनरावलोकनात',
        'status_assigned': 'अधिकारी नेमले',
        'status_in_progress': 'काम प्रगतीपथावर',
        'status_resolution_submitted': 'तोडगा सादर केला',
        'status_citizen_verification': 'नागरिक पडताळणी',
        'status_resolved': 'समस्या निवारण झाले',
        'status_verified': 'सत्यापित',
        'status_closed': 'बंद केले',
        'status_reopened': 'पुन्हा उघडले',
        'status_rejected': 'नाकारले',
        'assigned_officer': 'नियुक्त अधिकारी',
        'field_team': 'क्षेत्रीय पथक',
        'expected_resolution': 'अपेक्षित निराकरण वेळ (SLA)',
        'hours': 'तास',
        'days': 'दिवस',
        'verify_resolution': 'तोडगा पडताळा',
        'confirm_resolved': 'होय, समस्या सुटली',
        'not_resolved_reopen': 'अजूनही सुटले नाही (पुन्हा उघडा)',
        'resolution_notes': 'अधिकारी निराकरण नोंद',
        'resolution_evidence': 'काम पूर्ण झाल्याचा फोटो पुरावा',

        // Civic Feed & Community Map
        'civic_feed_title': 'स्थानिक नागरी फीड',
        'nearby_issues': 'परिसरातील नागरी समस्या',
        'support_issue': 'पाठिंबा द्या',
        'supported': 'पाठिंबा दिला',
        'upvotes': 'समर्थक',
        'filter_all': 'सर्व',
        'filter_nearby': 'जवळचे (२ किमी)',
        'filter_trending': 'सर्वाधिक पाठिंबा',
        'distance_away': 'लांब',
        'map_layers': 'नकाशा स्तर',
        'legend': 'संकेत सूची',

        // Profile & Credits
        'my_profile': 'माझी प्रोफाइल',
        'edit_profile': 'प्रोफाइल संपादित करा',
        'green_points': 'नागरी ग्रीन पॉईंट्स',
        'total_reports': 'एकूण तक्रारी',
        'resolved_count': 'सुटलेले',
        'in_progress_count': 'प्रगतीपथावर',
        'account_settings': 'खाते सेटिंग्ज',
        'privacy_policy': 'गोपनीयता धोरण',
        'terms_of_service': 'सेवा अटी',

        // Emergency Helpline
        'emergency_contacts': 'आपत्कालीन हेल्पलाईन क्रमांक',
        'ambulance': 'रुग्णवाहिका (वैद्यकीय)',
        'fire_brigade': 'अग्निशामक दल',
        'police_control': 'पोलीस नियंत्रण कक्ष',
        'municipal_helpline': 'महानगरपालिका २४x७ हेल्पलाईन',
        'disaster_mgmt': 'आपत्ती व्यवस्थापन कक्ष',

        // System, Feedback, Errors & Permissions
        'loading': 'लोड होत आहे...',
        'please_wait': 'कृपया प्रतीक्षा करा...',
        'network_error': 'नेटवर्क त्रुटी. कृपया पुन्हा प्रयत्न करा.',
        'location_error': 'स्थान अनुपलब्ध. कृपया GPS सुरू करा.',
        'permission_required': 'परवानगी आवश्यक',
        'camera_permission_msg': 'फोटो पुरावा जोडण्यासाठी कॅमेरा आणि स्टोरेज परवानगी आवश्यक आहे.',
        'success': 'यशस्वी',
        'error': 'त्रुटी',
        'retry': 'पुन्हा प्रयत्न करा',
        'cancel': 'रद्द करा',
        'confirm': 'पुष्टी करा',
        'close': 'बंद करा',
        'language_settings': 'भाषा सेटिंग्ज',
        'choose_language': 'आपली भाषा निवडा',
        'language_changed_to': 'भाषा बदलली',

        // Additional Auth & Login Keys in Marathi
        'app_tagline_login': 'सशक्त समुदाय, प्रत्येक तक्रारीसह.',
        'citizen_tab': 'नागरिक',
        'field_officer_tab': 'फील्ड अधिकारी',
        'sign_in_tab': 'साइन इन (आधार/OTP)',
        'sign_up_tab': 'नवीन नागरिक नोंदणी',
        'citizen_login_header': 'नागरिक लॉगिन',
        'field_officer_login_header': 'फील्ड अधिकारी / कंत्राटदार लॉगिन',
        'create_account_header': 'नागरिक खाते तयार करा',
        'join_municipal_desc': 'सत्यापित नागरिक योगदानकर्ता म्हणून आपल्या महापालिका क्षेत्रात सामील व्हा (स्कोअर 0 • 🌱 सिव्हिक स्टार्टर)',
        'full_legal_name_hint': 'पूर्ण अधिकृत नाव (उदा. विक्रम पाटील)',
        'mobile_number_hint': '१०-अंकी मोबाईल नंबर',
        'email_address_hint': 'ईमेल पत्ता (उदा. name@example.com)',
        'password_char_hint': 'पासवर्ड (किमान ६ अक्षरे)',
        'district_city_hint': 'जिल्हा / शहर',
        'ward_area_hint': 'प्रभाग / क्षेत्र',
        'register_enter_btn': 'नोंदणी करा आणि पोर्टलमध्ये प्रवेश करा',
        'aadhaar_input_hint': '१२-अंकी आधार क्रमांक',
        'login_with_aadhaar_btn': 'आधारने लॉगिन करा',
        'otp_sent_card_title': 'तुमच्या मोबाईलवर OTP पाठवला आहे',
        'otp_input_hint': '६-अंकी OTP (उदा. 123456)',
        'resend_otp_in_text': 'OTP पुन्हा पाठवा',
        'can_resend_otp_text': 'तुम्ही आता OTP पुन्हा पाठवू शकता',
        'resend_btn': 'पुन्हा पाठवा',
        'verify_login_btn': 'सत्यापित करा आणि लॉगिन करा',
        'change_aadhaar_btn': 'आधार क्रमांक बदला',
        'officer_id_hint': 'अधिकारी आयडी / ईमेल (उदा. demo.officer@civicresolve.gov)',
        'login_as_officer_btn': 'फील्ड अधिकारी म्हणून लॉगिन करा',
        'evaluator_access_title': 'परीक्षक त्वरित प्रवेश',
        'evaluator_access_desc': 'हॅकाथॉन मूल्यांकन आणि थेट चाचणीसाठी एक-टॅप नागरिक सत्र.',
        'evaluator_access_citizen_desc': 'हॅकाथॉन मूल्यांकन आणि थेट चाचणीसाठी एक-टॅप नागरिक सत्र.',
        'evaluator_access_officer_desc': 'महापालिका फील्ड कर्मचारी मूल्यांकन आणि थेट कार्य ट्रॅकिंगसाठी एक-टॅप फील्ड अधिकारी सत्र.',
        'one_tap_demo_btn': '⚡ वन-टॅप परीक्षक / डेमो लॉगिन',
        'one_tap_citizen_demo_btn': '⚡ वन-टॅप नागरिक डेमो लॉगिन',
        'one_tap_officer_demo_btn': '⚡ वन-टॅप फील्ड अधिकारी डेमो लॉगिन',

        // Additional Track Keys in Marathi
        'track_my_complaints': 'माझ्या तक्रारींचा मागोवा घ्या',
        'realtime_action_status': 'थेट महापालिका निवारण स्थिती',
        'search_complaints_hint': 'आयडी (#CR-...), शीर्षक, स्थानावरून शोधा...',
        'syncing_status': 'महापालिका प्रणालीवरून थेट स्थिती सिंक होत आहे...',
        'complaints_found': 'तक्रारी सापडल्या',
        'live_sync': 'थेट सिंक',
        'no_matching_complaints': 'कोणतीही जुळणारी तक्रार नाही',
        'no_complaints_yet_track': 'अद्याप कोणतीही तक्रार नाही',
        'try_changing_filters': 'कृपया शोध शब्द किंवा फिल्टर बदलून पहा.',
        'report_first_track_desc': 'आपली पहिली नागरिक समस्या नोंदवा आणि येथे तिचा मागोवा घ्या.',
        'clear_filters': 'फिल्टर काढा',
        'report_first_issue_btn': 'आपली पहिली तक्रार नोंदवा',
        'sort_newest': 'नवीनतम',
        'sort_oldest': 'जुने',
        'filter_submitted': 'सबमिट केले',
        'filter_under_review': 'तपासणी सुरू',
        'filter_assigned': 'अधिकारी नियुक्त',
        'filter_in_progress': 'काम प्रगतीपथावर',
        'filter_resolved': 'निवारण झाले',
        'filter_high_priority': 'उच्च प्राधान्य',

        // Additional Feed & Map Keys in Marathi
        'gps_off_showing_public': 'GPS बंद: सार्वजनिक तक्रारी दाखवत आहे',
        'enable_gps': 'GPS सुरू करा',
        'city_wide': 'शहरभर',
        'km_radius': 'किमी परिसर',
        'sort_most_supported': 'सर्वाधिक पाठिंबा',
        'sort_recent': 'नुकतेच',
        'sort_nearby': 'जवळचे',
        'search_feed_hint': 'शीर्षक, स्थान किंवा वर्णनानुसार शोधा...',
        'supported_issue_award': 'तक्रारीला पाठिंबा दिला! +२ नागरी प्रभाव गुण मिळाले.',
        'live_nearby_issues': 'परिसरातील थेट नागरी समस्या',
        'gis_reports_near_you': 'आपल्या जवळील रिअल-टाइम महापालिका जीआयएस अहवाल',
        'gps_unavailable_center': 'GPS अनुपलब्ध. महापालिका केंद्र दाखवले जात आहे.',
        'map_centered_gps': 'नकाशा आपल्या सध्याच्या GPS स्थानावर केंद्रित केला आहे.',
        'submit_feedback_comments': 'कृपया अभिप्राय नोंदवा.',
        'feedback_recorded': 'धन्यवाद! आपला अभिप्राय नोंदवला गेला आहे.',
        'enter_feedback_hint': 'अभिप्राय तपशील प्रविष्ट करा...',
        'rate_experience': 'निवारण दर्जाचे मूल्यांकन करा',
        'submit_feedback': 'अभिप्राय सादर करा',

        // Profile & Account Keys in Marathi
        'verified_citizen': 'सत्यापित नागरिक',
        'personal_info': 'वैयक्तिक माहिती',
        'date_of_birth': 'जन्म तारीख',
        'occupation': 'व्यवसाय',
        'member_since': 'सदस्यता कालावधी',
        'contact_info': 'संपर्क माहिती',
        'address': 'पत्ता',
        'community_activity': 'सामुदायिक उपक्रम',
        'reports_submitted_count': 'नोंदवलेल्या तक्रारी',
        'community_score': 'सामुदायिक स्कोअर',
        'green_credits_label': 'ग्रीन क्रेडिट्स',
        'civic_rewards_contributions': 'नागरी पुरस्कार व योगदान',
        'scores_auto_updated_desc': 'ऑन-साइट महानगरपालिका पथकांनी तक्रार किंवा तोडगा पडताळल्यानंतर गुण आपोआप अपडेट होतात.',
        'view_contribution_history_btn': 'योगदान इतिहास पहा',
        'plant_shop_btn': 'रोपवाटिका (प्लांट शॉप)',
        'edit_profile_btn': 'प्रोफाइल संपादित करा',
        'save_changes_btn': 'बदल जतन करा',
        'profile_updated_toast': 'प्रोफाइल यशस्वीरित्या अद्यतनित झाली',

        // Emergency Contacts Keys in Marathi
        'police_emergency': 'पोलीस आपत्कालीन',
        'police_emergency_desc': 'त्वरित पोलीस मदत आणि गुन्हेगारी तक्रारीसाठी',
        'medical_emergency': 'वैद्यकीय आपत्कालीन',
        'medical_emergency_desc': 'रुग्णवाहिका आणि आपत्कालीन वैद्यकीय सेवा',
        'fire_brigade_desc': 'अग्निशमन आणि बचाव कार्य',
        'disaster_mgmt_desc': 'नैसर्गिक आपत्ती व आपत्कालीन व्यवस्थापन',
        'women_helpline': 'महिला हेल्पलाईन',
        'women_helpline_desc': 'अडचणीत सापडलेल्या महिलांसाठी आपत्कालीन मदत',
        'child_helpline': 'बाल हेल्पलाईन',
        'child_helpline_desc': 'गरजू बालकांसाठी आपत्कालीन मदत',
        'tourist_emergency': 'पर्यटक हेल्पलाईन',
        'tourist_emergency_desc': 'पर्यटक सहाय्य आणि आपत्कालीन मदत',
        'senior_helpline': 'ज्येष्ठ नागरिक हेल्पलाईन',
        'senior_helpline_desc': 'ज्येष्ठ नागरिकांसाठी आपत्कालीन सहाय्य',
        'confirm_call': 'कॉलची पुष्टी करा',
        'are_you_sure_call': 'आपली खात्री आहे की आपण कॉल करू इच्छिता?',
        'call_now': 'आता कॉल करा',
        'connecting_to': 'जोडणी होत आहे',
        'emergency_tips': 'आपत्कालीन सल्ले',
        'stay_calm': 'शांत राहा',
        'stay_calm_desc': 'आपत्कालीन सेवांना कॉल करताना शांत राहा आणि स्पष्टपणे बोला',
        'know_location': 'आपले स्थान माहित ठेवा',
        'know_location_desc': 'आपले अचूक स्थान किंवा जवळील खूण सांगण्यासाठी तयार राहा',
        'have_info_ready': 'महत्त्वाची माहिती तयार ठेवा',
        'have_info_ready_desc': 'वैद्यकीय माहिती आणि आपत्कालीन संपर्क हाताशी ठेवा',
        'follow_instructions': 'सूचनांचे पालन करा',
        'follow_instructions_desc': 'लक्षपूर्वक ऐका आणि ऑपरेटरच्या सूचनांचे पालन करा',
        'dont_hang_up': 'कॉल कापू नका',
        'dont_hang_up_desc': 'ऑपरेटर सांगत नाही तोपर्यंत कॉल सुरू ठेवा',

        // Help & Support Keys in Marathi
        'were_here_to_help': 'आम्ही मदतीसाठी येथे आहोत',
        'help_intro_desc': 'उत्तरे शोधा, ॲप कसे वापरावे ते शिका आणि आमच्या मदत पथकाशी संपर्क साधा',
        'app_guide_tab': 'ॲप मार्गदर्शक',
        'faq_tab': 'नेहमी विचारले जाणारे प्रश्न',
        'contact_tab': 'संपर्क करा',
        'getting_started': 'सुरुवात कशी करावी',
        'step_create_profile': '१. आपली प्रोफाइल तयार करा',
        'step_create_profile_desc': 'मूलभूत माहितीसह आपले खाते सेट करा',
        'step_enable_location': '२. स्थान सेवा सक्षम करा',
        'step_enable_location_desc': 'अचूक तक्रारीसाठी लोकेशन परवानगी द्या',
        'step_report_issue': '३. समस्येची तक्रार करा',
        'step_report_issue_desc': 'फोटो काढा, वर्ग निवडा आणि तक्रार सादर करा',
        'step_track_progress': '४. प्रगती ट्रॅक करा',
        'step_track_progress_desc': 'थेट स्थिती आणि अधिकारी वाटप पहा',
        'step_verify_resolution': '५. तोडगा पडताळा',
        'step_verify_resolution_desc': 'झालेल्या कामाची पुष्टी करा आणि नागरी प्रभाव गुण मिळवा',

        // Notification Keys in Marathi
        'clear_all_notifications': 'सर्व सूचना काढा',
        'clear_all_confirm_desc': 'आपली खात्री आहे की आपण सर्व सूचना काढू इच्छिता? ही क्रिया पूर्ववत केली जाऊ शकत नाही.',
        'all_notifications_cleared': 'सर्व सूचना काढल्या गेल्या',
        'no_notifications_yet': 'अद्याप कोणतीही सूचना नाही',
        'all_caught_up': 'सर्व अद्ययावत आहे! आपल्या तक्रारींचे अपडेट्स येथे दिसतील.',

        // Map View Keys in Marathi
        'map_view_title': 'परिसरातील थेट नागरी समस्या',
        'map_view_subtitle': 'आपल्या जवळील रिअल-टाइम महापालिका जीआयएस अहवाल',
        'category_all': 'सर्व',
        'category_roads': 'रस्ते',
        'category_water': 'पाणी',
        'category_electricity': 'वीज',
        'category_sanitation': 'स्वच्छता',
        'category_safety': 'सुरक्षितता',
        'status_active': 'सक्रिय',
        'status_all': 'सर्व',
        'view_as_map': 'नकाशा दृश्य',
        'view_as_list': 'यादी दृश्य',
        'recenter_map': 'पुन्हा केंद्रित करा',

        // Common Form & Dialog Actions in Marathi
        'edit': 'संपादित करा',
        'camera': 'कॅमेरा',
        'gallery': 'गॅलरी',
        'select_location': 'स्थान निवडा',
        'confirm_location': 'स्थानाची पुष्टी करा',
        'location_confirmed': 'स्थान निश्चित झाले!',
        'quick_options': 'जलद पर्याय',
        'specific_address_label': 'विशिष्ट पत्ता किंवा खूण *',
        'fill_address': 'कृपया समस्येचा पत्ता द्या',
        'fill_specific_address': 'कृपया अधिक तपशीलवार पत्ता द्या',
        'fill_description': 'कृपया समस्येचे वर्णन करा',
        'fill_detailed_description': 'कृपया अधिक तपशीलवार वर्णन द्या (किमान १० अक्षरे)',
        'suggested_priority': 'सुचवलेला प्राधान्यक्रम',
        'ai_review_disclaimer': 'एआय सूचनांची महानगरपालिका कर्मचाऱ्यांद्वारे पडताळणी केली जाऊ शकते.',
        'gps_unavailable_fallback': 'महानगरपालिका केंद्र वापरत आहे (GPS अनुपलब्ध). अचूक स्थानासाठी नकाशा हलवा किंवा पत्ता संपादित करा.',
        'attached_evidence': 'जोडलेला पुरावा',
        'no_images_attached': 'कोणताही फोटो जोडलेला नाही.',
        'replace_photo_to_submit': 'दाखल करण्यासाठी फोटो बदला',
        'genuine_report_disclaimer': 'तक्रार दाखल करून, आपण पुष्टी करता की ही तक्रार खरी नागरी समस्या आहे.',
        'official_municipal_tracking': 'अधिकृत महानगरपालिका ट्रॅकिंग',
        'seven_stage_lifecycle': '७-टप्प्यांचे महानगरपालिका जीवनचक्र',
        'stage_1_title': '१. तक्रार नोंदवली',
        'stage_1_desc': 'CivicResolve महानगरपालिका तक्रार प्रणालीमध्ये नोंदवले.',
        'stage_2_title': '२. तपासणी सुरू',
        'stage_2_desc': 'महानगरपालिका कक्ष अधिकारक्षेत्र आणि प्राधान्य निश्चित करत आहे.',
        'stage_3_title': '३. विभाग व फील्ड अधिकाऱ्याकडे सोपवले',
        'stage_3_desc': 'संबंधित महानगरपालिका देखभाल विभागाकडे सोपवले.',
        'stage_4_title': '४. प्रत्यक्ष काम प्रगतीपथावर आहे',
        'stage_4_desc': 'क्षेत्रीय तपासणी व देखभाल पथक घटनास्थळी कार्यरत आहे.',
        'stage_5_title': '५. निवारण सादर केले',
        'stage_5_desc': 'क्षेत्रीय कंत्राटदाराने कामाचा फोटो पुरावा अपलोड केला आहे.',
        'stage_6_title': '६. निवारण पडताळणी',
        'stage_6_desc': 'पुरावा पडताळणी आणि नागरिक समाधान आढावा.',
        'stage_7_title': '७. अधिकृत पूर्णता / बंद',
        'stage_7_desc': 'समस्या यशस्वीरित्या सोडवली गेली आणि महानगरपालिकेद्वारे बंद करण्यात आली.',
        'submitted_location': 'तक्रारीचे नोंदवलेले स्थान',
        'awaiting_field_assignment': 'अधिकारी नेमणुकीची प्रतीक्षा आहे',
        'on_site_active': 'घटनास्थळी सक्रिय',
        'assigned_dispatched': 'नेमणूक झाली / रवाना',
        'remediation_submitted': 'निवारण पुरावा सादर केला',
        'officer_location_unavailable': 'अधिकाऱ्याचे स्थान अनुपलब्ध',
        'jurisdictional_cell_assessing': 'संबंधित महानगरपालिका कक्ष आढावा घेत आहे',
      },

      // Telugu, Tamil, Malayalam fallback to English if keys are not explicitly provided
      'te': {
        'app_name': 'CivicResolve',
        'app_slogan': 'మెరుగైన సంఘాలను కలిసి నిర్మిస్తున్నాము',
        'nav_home': 'హోమ్',
        'nav_report': 'నివేదిక',
        'nav_track': 'ట్రాక్',
        'nav_map': 'మ్యాప్',
        'nav_profile': 'ప్రొఫైల్',
      },
      'ta': {
        'app_name': 'CivicResolve',
        'app_slogan': 'சிறந்த சமூகங்களை ஒன்றாக உருவாக்குகிறோம்',
        'nav_home': 'முகப்பு',
        'nav_report': 'அறிக்கை',
        'nav_track': 'கண்காணிப்பு',
        'nav_map': 'வரைபடம்',
        'nav_profile': 'சுயவிவரம்',
      },
      'ml': {
        'app_name': 'CivicResolve',
        'app_slogan': 'മികച്ച കമ്മ്യൂണിറ്റികൾ ഒരുമിച്ച് നിർമ്മിക്കുന്നു',
        'nav_home': 'ഹോം',
        'nav_report': 'റിപ്പോർട്ട്',
        'nav_track': 'ട്രാക്ക്',
        'nav_map': 'മാപ്പ്',
        'nav_profile': 'പ്രൊഫൈൽ',
      },
    };
  }
}