-- DEPRECATED: Legacy plain-text auth migration decommissioned in Phase 13.
-- Supabase Auth uses bcrypt / cryptographic JWT tokens.
-- For staff account provisioning, use Supabase Auth Dashboard or secure backend scripts.